import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Clock3, DollarSign, Plus, RefreshCw, Send, X } from 'lucide-react';
import { useAuth } from '../../App';
import { approveCourtCost, createCourtCost, disputeCourtCost, getCases, getCourtCosts, markCourtCostPaid, requestCourtCostCorrection } from '../../lib/api';

const money = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value || 0));
const statuses = ['all', 'submitted', 'needs_correction', 'approved', 'awaiting_payment', 'paid', 'disputed'];
const labels = { submitted: 'Submitted', needs_correction: 'Needs correction', approved: 'Approved', awaiting_payment: 'Awaiting payment', paid: 'Paid', disputed: 'Disputed' };
const ETHAN_REFERRAL_PARTNER_ID = 'b61a812f-dba1-41b1-bbba-07bbb28a58a5';

export default function CourtCosts() {
  const { profile } = useAuth();
  const [rows, setRows] = useState([]); const [cases, setCases] = useState([]); const [filter, setFilter] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [showForm, setShowForm] = useState(false); const [selected, setSelected] = useState(null); const [form, setForm] = useState({ case_id: '', amount: '', expense_date: new Date().toISOString().slice(0, 10), court_name: '', description: '', receipt_url: '' });
  const privileged = profile?.role === 'attorney' || profile?.role === 'staff_attorney';

  async function load() { setLoading(true); setError(''); try { const [costs, caseRows] = await Promise.all([getCourtCosts(), getCases()]); setRows(Array.isArray(costs) ? costs : []); setCases(Array.isArray(caseRows) ? caseRows : []); } catch (err) { setError(err?.message || 'Could not load Court Costs.'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);

  const visible = useMemo(() => filter === 'all' ? rows : rows.filter((row) => row.status === filter), [rows, filter]);
  const ethanCases = useMemo(() => cases.filter((item) => item.referral_partner_id === ETHAN_REFERRAL_PARTNER_ID), [cases]);
  const caseCosts = useMemo(() => rows.reduce((map, row) => { if (row.case_id) map[row.case_id] = [...(map[row.case_id] || []), row]; return map; }, {}), [rows]);
  const totals = useMemo(() => ({ submitted: rows.filter((r) => r.status === 'submitted').reduce((s, r) => s + Number(r.amount || 0), 0), outstanding: rows.filter((r) => !['paid'].includes(r.status)).reduce((s, r) => s + Number(r.amount || 0), 0), paid: rows.filter((r) => r.status === 'paid').reduce((s, r) => s + Number(r.paid_amount || r.amount || 0), 0) }), [rows]);
  const setField = (key, value) => setForm((current) => ({ ...current, [key]: value }));

  async function submit(event) { event.preventDefault(); setError(''); setNotice(''); try { const created = await createCourtCost({ ...form, amount: Number(form.amount), status: 'submitted' }); setRows((current) => [created, ...current]); setShowForm(false); setForm({ case_id: '', amount: '', expense_date: new Date().toISOString().slice(0, 10), court_name: '', description: '', receipt_url: '' }); setNotice('Court-cost request submitted. The referral partner and owner were notified.'); } catch (err) { setError(err?.message || 'Could not submit the court-cost request.'); } }
  async function action(row, nextStatus, extra = {}) { setError(''); setNotice(''); try { const updated = await (nextStatus === 'paid' ? markCourtCostPaid(row.id, extra) : nextStatus === 'approved' ? approveCourtCost(row.id) : nextStatus === 'needs_correction' ? requestCourtCostCorrection(row.id, extra.note) : disputeCourtCost(row.id, extra.note)); setRows((current) => current.map((item) => item.id === row.id ? updated : item)); setSelected(null); setNotice(nextStatus === 'paid' ? 'Marked paid. Esther and the owner were notified.' : 'Court-cost request updated.'); } catch (err) { setError(err?.message || 'Could not update this request.'); } }
  function pay(row) { const amount = window.prompt(`Amount paid for ${row.case_label || 'this matter'}:`, String(row.amount || '')); if (amount === null) return; const paymentDate = window.prompt('Payment date (YYYY-MM-DD):', new Date().toISOString().slice(0, 10)); if (paymentDate === null) return; action(row, 'paid', { paid_amount: Number(amount), payment_date: paymentDate, payment_method: 'External payment' }); }
  function openCostForm(caseId = '') { setForm((current) => ({ ...current, case_id: caseId })); setShowForm(true); }

  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-2xl bg-slate-950 px-6 py-6 text-white shadow-lg"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-200">Shared reimbursement workspace</p><h1 className="mt-2 text-2xl font-bold">Court Costs</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Submit, review, and track court-cost reimbursements across Esther, Ethan, and the LegalFlow owner account.</p></div><div className="flex gap-2"><button type="button" onClick={() => setShowForm(true)} className="inline-flex items-center gap-2 rounded-lg bg-white px-3.5 py-2 text-sm font-semibold text-slate-900"><Plus className="h-4 w-4" />Submit cost</button><button type="button" onClick={load} className="rounded-lg border border-slate-600 p-2 text-white"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></button></div></div><div className="mt-6 grid gap-4 border-t border-slate-800 pt-5 md:grid-cols-3"><div><p className="text-xs uppercase tracking-wide text-slate-400">Submitted</p><p className="mt-1 text-2xl font-bold">{money(totals.submitted)}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-400">Outstanding</p><p className="mt-1 text-2xl font-bold text-amber-300">{money(totals.outstanding)}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-400">Paid</p><p className="mt-1 text-2xl font-bold text-emerald-300">{money(totals.paid)}</p></div></div></header>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle className="mr-1 inline h-4 w-4" />{error}</div>}{notice && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="mr-1 inline h-4 w-4" />{notice}</div>}
    {ethanCases.length > 0 && <section className="rounded-2xl border border-indigo-200 bg-indigo-50/50 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-indigo-100 p-5"><div><h2 className="text-lg font-bold text-slate-900">Ethan Babb’s Cases</h2><p className="mt-1 text-sm text-slate-600">Cases are loaded automatically. Select a row to record court costs without searching through a dropdown.</p></div><span className="rounded-full bg-indigo-100 px-3 py-1 text-xs font-bold text-indigo-700">{ethanCases.length} cases</span></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-white text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Case / client</th><th className="px-4 py-3">Pipeline status</th><th className="px-4 py-3">Court-cost requests</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-indigo-100 bg-white">{ethanCases.map((item) => { const itemCosts = caseCosts[item.id] || []; return <tr key={item.id} className="hover:bg-indigo-50"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{item.plaintiff_name || item.client_name || 'Unnamed client'}</p><p className="mt-1 text-xs text-slate-500">{item.case_number || item.id}</p></td><td className="px-4 py-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700">{item.status || 'No status'}</span></td><td className="px-4 py-4"><p className="font-semibold text-slate-900">{itemCosts.length ? money(itemCosts.reduce((sum, cost) => sum + Number(cost.amount || 0), 0)) : 'None recorded'}</p><p className="text-xs text-slate-500">{itemCosts.length} request{itemCosts.length === 1 ? '' : 's'}</p></td><td className="px-4 py-4 text-right"><button type="button" onClick={() => openCostForm(item.id)} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white hover:bg-indigo-700">Record court cost</button></td></tr>; })}</tbody></table></div></section>}
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap gap-2 border-b border-slate-100 p-5">{statuses.map((value) => <button key={value} type="button" onClick={() => setFilter(value)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${filter === value ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-600'}`}>{value === 'all' ? 'All' : labels[value]}</button>)}</div>{loading ? <div className="p-8 text-center text-sm text-slate-500">Loading Court Costs…</div> : visible.length === 0 ? <div className="p-8 text-center text-sm text-slate-500">No court-cost requests in this view.</div> : <div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Case / client</th><th className="px-4 py-3">Cost</th><th className="px-4 py-3">Referral partner</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Submitted</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{row.case_label}</p><p className="mt-1 text-xs text-slate-500">{row.client_name}</p><p className="mt-1 text-xs text-slate-400">{row.court_name} · {row.expense_date}</p></td><td className="px-4 py-4"><p className="font-semibold">{money(row.amount)}</p><p className="text-xs text-slate-500">{row.description}</p></td><td className="px-4 py-4"><p className="font-semibold">{row.referral_partner?.full_name || 'Unassigned'}</p><p className="text-xs text-slate-500">{row.referral_partner?.email || 'Assign a referral partner'}</p></td><td className="px-4 py-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{labels[row.status] || row.status}</span></td><td className="px-4 py-4 text-xs text-slate-500">{row.submitted_at ? new Date(row.submitted_at).toLocaleDateString() : 'Draft'}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{privileged && ['submitted', 'awaiting_payment'].includes(row.status) && <button type="button" onClick={() => action(row, 'approved')} className="rounded-lg bg-indigo-600 px-2.5 py-1.5 text-xs font-semibold text-white">Approve</button>}{privileged && row.status !== 'paid' && <button type="button" onClick={() => pay(row)} className="rounded-lg bg-emerald-600 px-2.5 py-1.5 text-xs font-semibold text-white">Mark paid</button>}<button type="button" onClick={() => setSelected(row)} className="rounded-lg border border-slate-300 px-2.5 py-1.5 text-xs font-semibold text-slate-700">Details</button></div></td></tr>)}</tbody></table></div>}</section>
    {showForm && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-2xl space-y-4 rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Submit court-cost request</h2><button type="button" onClick={() => setShowForm(false)}><X className="h-5 w-5" /></button></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Case{form.case_id ? <div className="mt-1 flex items-center justify-between rounded-lg border border-indigo-200 bg-indigo-50 p-3"><span className="font-semibold text-indigo-900">{cases.find((item) => item.id === form.case_id)?.plaintiff_name || cases.find((item) => item.id === form.case_id)?.case_number || form.case_id}</span><button type="button" onClick={() => setField('case_id', '')} className="text-xs font-semibold text-indigo-700 underline">Change</button></div> : <select required value={form.case_id} onChange={(e) => setField('case_id', e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value="">Select a case</option>{cases.map((item) => <option key={item.id} value={item.id}>{item.case_number || item.plaintiff_name || item.id}</option>)}</select>}</label><label className="text-sm font-medium">Amount<input required type="number" min="0" step="0.01" value={form.amount} onChange={(e) => setField('amount', e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-medium">Expense date<input required type="date" value={form.expense_date} onChange={(e) => setField('expense_date', e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-medium">Court name<input required value={form.court_name} onChange={(e) => setField('court_name', e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label></div><label className="block text-sm font-medium">Description<textarea required value={form.description} onChange={(e) => setField('description', e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border p-2" placeholder="What was paid and why?" /></label><label className="block text-sm font-medium">Receipt link (optional)<input value={form.receipt_url} onChange={(e) => setField('receipt_url', e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><button className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white"><Send className="h-4 w-4" />Submit and notify</button></form></div>}
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Court-cost details</h2><button type="button" onClick={() => setSelected(null)}><X className="h-5 w-5" /></button></div><p className="mt-4 text-sm text-slate-600">{selected.description}</p>{selected.correction_note && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Correction note: {selected.correction_note}</p>}<div className="mt-5 space-y-3">{selected.events?.map((event) => <div key={event.id} className="flex gap-3 border-b pb-3 text-sm"><Clock3 className="mt-0.5 h-4 w-4 text-slate-400" /><div><p className="font-semibold">{labels[event.to_status] || event.action}</p><p className="text-xs text-slate-500">{new Date(event.created_at).toLocaleString()} {event.note || ''}</p></div></div>)}</div>{!privileged && selected.status === 'needs_correction' && <button type="button" onClick={() => setSelected(null)} className="mt-5 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white">Close and correct</button>}{privileged && selected.status !== 'paid' && <button type="button" onClick={() => pay(selected)} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white"><DollarSign className="h-4 w-4" />Mark paid</button>}</div></div>}
  </div>;
}
